// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6TSpzNKy29y61ZBXEezzVXnIpL93BsAc',
    appId: '1:809261373679:web:a66f4174a26b70a9af631a',
    messagingSenderId: '809261373679',
    projectId: 'work-c2e2b',
    authDomain: 'work-c2e2b.firebaseapp.com',
    storageBucket: 'work-c2e2b.firebasestorage.app',
    measurementId: 'G-T958NEWBKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSV4V-pFOhfi1FWd4wPhbiLphS6ot9xTI',
    appId: '1:809261373679:android:792c1d311613fe50af631a',
    messagingSenderId: '809261373679',
    projectId: 'work-c2e2b',
    storageBucket: 'work-c2e2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH_YjYjnIXnnPqskXTbtMJ7ZhY7mblRvE',
    appId: '1:809261373679:ios:e73cb860ee5b6735af631a',
    messagingSenderId: '809261373679',
    projectId: 'work-c2e2b',
    storageBucket: 'work-c2e2b.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH_YjYjnIXnnPqskXTbtMJ7ZhY7mblRvE',
    appId: '1:809261373679:ios:e73cb860ee5b6735af631a',
    messagingSenderId: '809261373679',
    projectId: 'work-c2e2b',
    storageBucket: 'work-c2e2b.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6TSpzNKy29y61ZBXEezzVXnIpL93BsAc',
    appId: '1:809261373679:web:22c8d98e83d5a03aaf631a',
    messagingSenderId: '809261373679',
    projectId: 'work-c2e2b',
    authDomain: 'work-c2e2b.firebaseapp.com',
    storageBucket: 'work-c2e2b.firebasestorage.app',
    measurementId: 'G-HX3MXDPEDT',
  );

}